<a href="https://colab.research.google.com/github/alawipot/datasci_1_loading/blob/main/HHA507.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**The following code cell below imports pandas and json**

we need pandas because we cannot load our datasets without it

we need json to be able to to read json files

In [ ]:
import pandas as pd
import json

In [ ]:
import pandas as pd
import json
import pandas as pd

df1 = '/content/Social_media_impact_on_life.csv'
read_df1 = pd.read_csv (df1)
read_df1.head (11)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
5,STU_2024005,16,Male,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial
6,STU_2024006,20,Male,Undergraduate,TikTok,5.6,1.8,Smartphone,8.3,3,False,Sometimes,10.0,88,3.72,Beneficial
7,STU_2024007,19,Female,Undergraduate,TikTok,1.2,2.4,Smartphone,8.1,5,False,Always,6.0,95,3.37,Beneficial
8,STU_2024008,18,Female,Undergraduate,YouTube,3.3,1.8,Smartphone,6.4,2,False,Frequently,23.0,88,3.59,Beneficial
9,STU_2024009,18,Female,Undergraduate,Reddit,4.7,1.7,Smartphone,7.9,2,False,Frequently,6.0,96,3.66,Beneficial
10,STU_2024010,15,Female,High School,TikTok,4.4,1.9,Smartphone,5.8,2,False,Frequently,11.0,83,3.22,Beneficial

**CSV_data1 represents the following**

General information about social media impact on life.

**Columns**

**1. Student ID**

 * This column designates each student a seven-digit identification code to protect their privacy.

 **2. Age**

 * This column provides the age of the student.

 **3. Gender**

 * This column provides the gender of the student.

 **4. Academic_Level**

 * This column provides the category of school the student is currently in - either high school or undergraduate.

 **5. Primary_Platform**

 * This column provides the primary social media platform that the student engages in during the week.

 **6. Daily_Usage_Hours**

 * This column provides the number of hours the student engages on their primary platform on a daily basis.

 **7. Weekend_Extra_Hours**

 * This column provides the number of additional hours the student engages on their primary platform during the weekends.

 **8. Device_Type**

 * This column provides the type of device that the student engages with social media on - either smartphone or tablet.  

 **9. Sleep_Duration_Hours**

 * This column provides the number of hours the student slept each night on average.

 **10. Sleep_Quality_Score**

 * This column provides the student's sleep quality score that summarizes how well you slept and recovered the previous night.


**11. Late_Night_Usage**

* This column serves to verify if the student was using social media late at night.


**12. Social_Comparison_Frequency**

* This column provided information on how frequently, if at all, the student compared themselves to others they viewed online.


**13. Perceived_Stress_Score**

* This column provides information on the perceived level of stress the student experienced as a result of using social media.


**14. Mental_Health_Index**

* This column provided the mental health index score of the student. This index is a data tool that measures mental well-being, risk factors, or program effectiveness for a specific group or location of individuals (in this case, students).


**15. Academic_Performance_GPA**

* This column provided an indication of how well the student performed academically in conjunction with their level of use of social media.


**16. Overall_Impact**

* This column provided an adjective to describe the overall impact of social media on the student as a whole.

In [ ]:
import pandas as pd
import json
import pandas as pd

df2 = '/content/bedtime_screentime_sleep_debt.csv'
read_df2 = pd.read_csv (df1)
read_df2.head (11)

,user_id,age,gender,occupation_type,chronotype,bedtime_phone_minutes,primary_bedtime_app,screen_brightness_pct,blue_light_filter_active,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,deep_sleep_pct,rem_sleep_pct,morning_alarm_snoozes,next_day_fatigue_score,sleep_debt_category
0,USR-00001,29,Female,Healthcare / Shift Worker,Intermediate,179,Instagram / Reddit,54,1,0,21,84.4,3.20,23.5,22.2,7,10.0,Severe Sleep Debt
1,USR-00002,58,Female,Student,Intermediate,163,YouTube,76,1,92,72,86.7,4.06,18.0,21.5,7,10.0,Severe Sleep Debt
2,USR-00003,41,Female,Healthcare / Shift Worker,Night Owl,100,TikTok / Reels,59,0,45,23,70.5,3.20,18.1,20.5,7,10.0,Severe Sleep Debt
3,USR-00004,36,Non-Binary,Remote Tech,Intermediate,34,YouTube,52,0,97,49,38.1,6.99,21.6,22.4,1,1.7,Mild Deficit
4,USR-00005,23,Female,Healthcare / Shift Worker,Intermediate,27,TikTok / Reels,82,1,0,38,32.3,4.58,24.1,22.8,4,5.3,Moderate Debt
5,USR-00006,23,Male,Healthcare / Shift Worker,Intermediate,76,TikTok / Reels,39,0,136,42,50.6,5.87,21.4,17.5,4,5.0,Moderate Debt
6,USR-00007,20,Female,Remote Tech,Night Owl,53,TikTok / Reels,32,0,0,64,36.2,4.43,22.7,19.0,6,6.4,Moderate Debt
7,USR-00008,49,Male,Remote Tech,Morning Lark,113,YouTube,34,1,39,58,60.2,5.94,19.3,19.9,3,4.5,Moderate Debt
8,USR-00009,36,Male,Freelance / Creative,Morning Lark,65,News / Reading,35,1,0,25,28.2,8.00,22.2,18.5,1,1.0,Optimal Recovery
9,USR-00010,40,Female,Student,Night Owl,70,Streaming (Netflix/Hulu),63,1,115,59,53.7,4.70,23.5,16.6,4,7.3,Moderate Debt
10,USR-00011,18,Female,Freelance / Creative,Intermediate,23,YouTube,49,0,0,34,19.7,7.54,25.4,22.1,2,1.0,Mild Deficit

**CSV_data2 represents the following**

General information about the effects of bedtime screentime on sleep debt.

**Columns**

**1. User ID**

* This column designates study participant an arbitrary digital number to protect their health information and private identity.

**2. Age**

* This column provides the age of the participant.

**3. Gender**

* This column provides the gender of the participant.

**4. Occupation_Type**

* This column provides the type of occupation of the participant.

**5. Chronotype**

* This column provides the type of sleep-wake pattern of the participant. Chronotype by definition is an individual's body's natural, genetically predetermined preference for when to sleep and wake up during a 24-hour day.

**6. Bedtime_Phone_Minutes**

* This column provides the average number of minutes the participant was on their phone during bedtime.

**7. Primary_Bedtime_App**

* This column provides information about the participant's primary bedtime app - what they tend to use the most at this time of their day.

**8. Screen_Brightness_Pct**

* This column provides information about the percentage of screen brightness with which the participant was operating their phone at bedtime.

**9. Blue_Light_Filter_Active**

* This column indicates whether the participant had their blue light filter active during their time of usage. Blue light filter is an active display setting that reduces the amount of high-energy short-wavelength bluelight emitted from a screen.

**10. Caffeine_post_5pm_mg**

* This column takes into consideration the effect of caffeine consumption a participant had in the evening hours.

**11. Physical_Activity_Min**

* This column monitors how many minutes of physical activity the participant engaged in during the day.

**12. Sleep_Latency_Min**

* This column measures the amount of time it takes the participant to transition from full wakeness to the very first stage of sleep after they turn off the lights and try to rest.

**13. Total_Sleep_Hours**

* This column indicates the average total number of sleep hours the participant had each night.

**14. Deep_Sleep_Pct**

* This column indicates the percentage of deep sleep the participant experienced on average at night. Deep sleep is the most physically restorative stage of sleep.

**15. REM_Sleep_Pct**

* This column indicates the percent of REM sleep the participant experienced on average at night. REM sleep is the active phase of the sleep cycle when the most vivid dreams occur.

**16. Morning_Alarm_Snoozes**

* This column indicates on average how many times the participant hit the snooze button on the alarm clock in the morning to wake up.

**17. Next_Day_Fatigue_Score**

* This column indicates the participant's next day fatigue score. This score is a predictive metric used in digital health and sleep research to estimate how tired or low-energy a person will feel on the following day based on current biometric data.

**18. Sleep_Debt_Category**

* This column uses a descriptive adjective to describe the severity of sleep debt of the participant.

In [12]:
import pandas as pd
import json
import pandas as pd

df3 = '/content/StudentsPerformance.csv'
read_df3 = pd.read_csv (df3)
read_df3.head (11)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52

**CSV_data3 represents the following**

General information about the factors that influence student performance.

**Columns**

**1. Gender**

* This column provides information about the gender of the student.

**2. Race/Ethnicity**

* This column provides information about the cultural and racial background of the student.

**3. Parental Level of Education**

* This column provides information about the parental level of education of the student.

**4. Lunch**

* This column provides information about whether the student had been provided lunch to take to school.

**5. Test Preparation Course**

* This column indicates whether the student had any access to preparatory courses prior to the examination.

**6. Math Score**

* This column provides information about the results of the student's mathematical performance.

**7. Reading Score**

* This column provides information about the results of the student's reading performance.

**8. Writing Score**

* This column provides information about the results of the student's writing performance.

In [18]:
df4 = '/content/cars.json'
read_df4 = pd.read_json(df4)
read_df4.head(11)

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA
5,ford galaxie 500,15.0,8,429.0,198.0,4341,10.0,1970-01-01,USA
6,chevrolet impala,14.0,8,454.0,220.0,4354,9.0,1970-01-01,USA
7,plymouth fury iii,14.0,8,440.0,215.0,4312,8.5,1970-01-01,USA
8,pontiac catalina,14.0,8,455.0,225.0,4425,10.0,1970-01-01,USA
9,amc ambassador dpl,15.0,8,390.0,190.0,3850,8.5,1970-01-01,USA
10,citroen ds-21 pallas,NaN,4,133.0,115.0,3090,17.5,1970-01-01,Europe

**Json_data4 represents the following**

General information about the features of different cars and how they compare.

**Columns**

**1. Name**

* This column provides the name of the make and model of the car.

**2. Miles_Per_Gallon**

* This column provides information about the number of miles the car can travel on a single gallon of fuel.

**3. Cylinders**

* This column provides information about how many cylinders the car has. The cylinders are the core power chambers in a car's engine where fuel and air burn to create mechanical energy and move the vehicle.

**4. Displacement**

* This column tells about the car's displacement. Car displacement refers to the total amount of fuel and air swept by all the pistons inside in an engine's cylinder during a complete cycle. It is the standard way to measure the size of a car's engine. It is measured in liters or cubic centimeters.  

**5. Horsepower**

* This column provides information about how much horsepower the car carries. Horsepower is a reference to how fast an engine can do work and generate power to move the car.

**6. Weight_in_Pounds**

* This column provides information regarding the weight of the car in pounds.

**7. Acceleration**

* This column tells about the rate of acceleration for the car.

**8. Year**

* This column tells what year the car was manufactured.

**9. Origin**

* This column provides information about the nation of origin of the car - where it was manufactured.

In [23]:
df5 = '/content/obesity.json'
read_df5 = pd.read_json(df5)
read_df5.head(11)

    id   rate state
0    1  0.187    AL
1    2  0.198    AK
2    4  0.133    AZ
3    5  0.175    AR
4    6  0.151    CA
5    8  0.100    CO
6    9  0.125    CT
7   10  0.171    DE
8   12  0.172    FL
9   13  0.133    GA
10  15  0.108    HI

**Json_data5 represents the following**

General information about the rates of obesity in various states.

**Columns**

**1. ID**

This column provides an arbitrarily assigned identifier.

**2. Rate**

This column provides the rate of obesity in the state as a decimal.

**3. State**

* This column provides the name of the state where rate of obesity was measured.

In [39]:
df6 = '/content/volcano.json'
read_df6 = pd.read_json(df6)
read_df6.head(11)

    width  height  values
0      87      61     103
1      87      61     104
2      87      61     104
3      87      61     105
4      87      61     105
5      87      61     106
6      87      61     106
7      87      61     106
8      87      61     107
9      87      61     107
10     87      61     106

**Json_data6 represents the following**

General information about the measurements of a group of volcanoes.

**Columns**

**1. Width**

* This column provides information about the width of the volcano in meters.

**2. Height**

* This column provides information about the height of the volcano in meters.

**3. Values**

* This column provides information about the values of the volcano. Scientists use the word values when referring to the quantitative measurements of the volcano.

In [20]:
df7 = '/content/01 Retail Inventory.xlsx'
read_df7 = pd.read_excel(df7)
read_df7.head(11)

,Product ID,Product Name,Category,Supplier Name,Unit Cost,Retail Price,Opening Stock,Units Sold,Closing Stock,Reorder Point,Stock Status
0,PRD-1001,Wine Glasses,Home & Kitchen,Heritage Brands,23.78,38.89,135,118,17,30,Low Stock
1,PRD-1002,Eye Mask,Beauty,Coastal Trading,15.67,24.53,86,10,76,9,In Stock
2,PRD-1003,Resistance Band,Sports & Outdoors,National Supply Group,5.59,11.88,319,195,124,47,In Stock
3,PRD-1004,Action Figure,Toys & Games,Pacific Wholesale,9.72,18.01,173,140,33,39,Low Stock
4,PRD-1005,Serving Tray,Home & Kitchen,Coastal Trading,8.22,13.90,32,8,24,7,In Stock
5,PRD-1006,Dried Fruit,Grocery,National Supply Group,6.94,12.18,74,52,22,15,In Stock
6,PRD-1007,Dish Soap,Home & Kitchen,Pacific Wholesale,6.74,13.47,21,6,15,2,In Stock
7,PRD-1008,Hiking Socks,Sports & Outdoors,National Supply Group,7.23,9.67,353,72,281,51,In Stock
8,PRD-1009,Dried Fruit,Grocery,Summit Wholesale Inc,10.60,16.76,196,59,137,26,In Stock
9,PRD-1010,Yoga Block,Sports & Outdoors,Premier Merchandise,5.54,9.54,38,14,24,4,In Stock
10,PRD-1011,Kitchen Towels,Home & Kitchen,Premier Merchandise,9.67,14.73,150,83,67,28,In Stock

**ExcelData7 represents the following**

This dataset provides information about the retail inventory of a store.

**Columns**

**1. Product ID**

* This column tells the a unique alphanumeric code assigned to a specific item to track it, manage inventory, or look it up in a database.

**2. Product Name**

* This column provides the product name. The product name is the specific title given to an item or data package to identify it easily.

**3. Category**

* This column provides information about which category the product falls under. The category refers to a high-level grouping of products that share similar characteristics, uses, or customer target markets.

**4. Supplier Name**

* This column shares the supplier name of the product. A supplier name is the official business name of the manufacturer, vendor, or distributor that provides goods or raw materials to another company

**5. Unit Cost**

* This column shares the unit cost of the product. Unit cost is the total amount of money it costs a company to produce, buy, or source a single individual unit of a product.

**6. Retail Price**

* This column conveys the retail price of the product. Retail price is the final amount of money a consumer pays to purchase a single unit of a product at a store or online.

**7. Opening Stock**

* This column refers to what is also known as "beginning stock." It is the total monetary value or quantity of products that a business has on hand and available for sale at the very start of a specific accounting period (such as a new month, quarter, or fiscal year).

**8. Units Sold**

* This column refers to the total quantity of individual items purchased by customers during a specific timeframe (e.g., daily, monthly, or annually). It tracks product demand and is directly used to calculate total sales revenue.

**9. Closing Stock**

* This column provides information regarding the total value or physical quantity of products remaining on hand and available for sale at the very end of an accounting period. The closing stock of one period automatically becomes the opening stock of the next period.

**10. Reorder Point**

* This column refers to the specific minimum inventory level that triggers the need to buy more stock from a supplier. It is calculated based on how fast the product sells (demand) and how long it takes the supplier to deliver it (lead time) to ensure the store never runs out of stock.

**11. Stock Status**

* This column refers to the current availability of an item in an inventory system.

In [41]:
df8 = '/content/03 Real Estate Listings.xlsx'
read_df8 = pd.read_excel(df8)
read_df8.head(11)

,Listing ID,Property Type,City,State,Bedrooms,Bathrooms,Square Footage,Year Built,List Price,Sale Price,Listing Status
0,LST-5001,House,Aurora,Illinois,3,1.5,1091,1971,351000,360000.0,Sold
1,LST-5002,House,Bellevue,Washington,4,3.5,2162,1960,709000,701000.0,Sold
2,LST-5003,House,Spokane,Washington,4,3.0,2301,2006,1232000,1165000.0,Sold
3,LST-5004,Condo,Buffalo,New York,1,1.0,437,1980,200000,190000.0,Pending
4,LST-5005,House,Rockford,Illinois,2,1.0,989,2025,451000,NaN,Active
5,LST-5006,House,Naperville,Illinois,4,3.0,1872,1966,334000,NaN,Active
6,LST-5007,House,Aurora,Colorado,4,3.0,1776,2013,1237000,1246000.0,Pending
7,LST-5008,Apartment,Mesa,Arizona,3,2.0,1022,1977,145000,138000.0,Sold
8,LST-5009,Apartment,Chandler,Arizona,1,1.5,252,2005,83000,85000.0,Pending
9,LST-5010,House,Albany,New York,3,1.5,1480,1978,799000,843000.0,Sold
10,LST-5011,Condo,Athens,Georgia,1,1.0,367,2013,71000,71000.0,Sold

**ExcelData8 represents the following**

This dataset provides information about the prices that homes in various city and states sold for in the country.

**Columns**

**1. Listing ID**

* This column provides the listing ID for the home. A listing ID is a unique string of numbers or letters assigned to a specific item, property, job, or service post on an online platform.

**2. Property Type**

This column talks about the property type of dwelling that is placed on the market. Property type refers to the specific classification or category of a piece of real estate, based on its design, structure, and intended use. It can be a condo, apartment, or house.

**3. City**

* This column refers to the city in which the property is located.

**4. State**

This column refers to the state in which the property is located.

**5. Bedrooms**

This column refers to the number of bedrooms the property type has.

**6. Bathrooms**

This column refers to the number of bathrooms situated on the property.

**7. Square Footage**

* This column refers to the size of the property. Square footage is a measurement of area that represents the total amount of livable, usable, or buildable space inside a property. It is calculated by multiplying the length of a room or space by its width in feet.

**8. Year Built**

* This column refers to the year in which the property was built.

**9. List Price**

* This column refers to the amount that the property was listed for sale on the market.

**10. Sale Price**

* This column refers to the actual price the buyer had agreed to purchase the property for.  

**11. Price Sold**

* This column refers to the exact dollar amount a buyer paid to purchase a property, finalized at the closing of the real estate transaction.

In [42]:
df9 = '/content/07 Supply Chain.xlsx'
read_df9 = pd.read_excel(df9)
read_df9.head(11)

,Shipment ID,Order Date,Supplier Name,Product Category,Quantity,Total Cost,Ship Date,Delivery Date,Shipping Carrier,Shipping Mode,On-Time Delivery
0,SHP-40001,2024-07-06,Frontier Chemical Supply,Chemicals,2968,771.78,2024-07-08,2024-08-21,UPS,Sea,No
1,SHP-40002,2025-02-19,Midwest Industrial,Packaging,2059,1960.20,2025-02-22,2025-02-24,UPS,Road,Yes
2,SHP-40003,2025-10-26,Summit Electronics,Chemicals,4046,3253.23,2025-10-29,2025-11-16,FedEx,Sea,Yes
3,SHP-40004,2024-12-31,Continental Distributors,Machinery,4494,6248.57,2025-01-02,2025-01-09,Local,Road,Yes
4,SHP-40005,2024-04-20,Reliable Metals Corp,Automotive Parts,927,6853.79,2024-04-22,2024-04-28,UPS,Road,Yes
5,SHP-40006,2024-03-27,Summit Electronics,Electronics,3919,23291.97,2024-03-28,2024-03-30,Local,Road,Yes
6,SHP-40007,2024-07-09,Frontier Chemical Supply,Automotive Parts,4192,18586.28,2024-07-10,2024-07-16,UPS,Rail,Yes
7,SHP-40008,2025-01-24,Midwest Industrial,Textiles,372,5850.56,2025-01-26,2025-02-07,FedEx,Rail,Yes
8,SHP-40009,2025-04-12,Reliable Metals Corp,Machinery,1800,8869.92,2025-04-15,2025-04-25,DHL,Rail,Yes
9,SHP-40010,2025-03-19,Frontier Chemical Supply,Raw Materials,1503,8566.53,2025-03-22,2025-03-30,Local,Road,Yes
10,SHP-40011,2024-04-27,Atlas Manufacturing,Raw Materials,10,9370.82,2024-04-28,2024-05-05,FedEx,Road,Yes

**ExcelData9 represents the following**

This dataset provides information about a supply chain's business transactions. A supply chain is the entire network of individuals, organizations, resources, activities, and technologies involved in creating and delivering a product from the raw material stage all the way to the final customer

**Columns**

**1. Shipment ID**

* This column refers to the identifying number a shipment was given.

**2. Order Date**

* This column refers to the date the item was ordered.

**3. Supplier Name**

* This column refers to the name of the supplier of goods.

**4. Product Category**

* This column refers to the type and class of product that was shipped.

**5. Quantity**

* This column provides information on how many items were shipped.

**6. Total Cost**

* This column refers to the total cost of shipment of goods.

**7. Ship Date**

* This column provides the date the shipment was sent out.

**8. Delivery Date**

* This column provides the date the shipment was actually delivered to the recipient.

**9. Shipping Carrier**

* This column provides information about who was the responsible party for shipping goods.

**10. Shipping Mode**

* This column provides information about how the goods were shipped - over sea or by railroad.

**11. On-Time Delivery**

* This column provides information about whether the goods were delivered on time or not.

****